server:
  port: 9001
spring:
  application:
    name: nacos-getaway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848