server:
  port: 9001
  ssl:
    client-auth:


# 不允许被访问的地址:
auth:
  noAccess:


# 不需要传入Token的地址
filter:
  noAuthor:
    - login
spring:
  application:
    name: nacos-getaway
  cloud:
    gateway:
      httpclient:
        # 如果5秒没有请求或者响应超过5秒
        connect-timeout: 5000
        response-timeout: 5000
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000


