server:
  port: 9001
spring:
  application:
    name: nacos-getaway
  cloud:
    gateway:
      httpclient:
        # 如果5秒没有请求或者响应超过5秒
        connect-timeout: 5000
        response-timeout: 5000
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos-student
          uri: lb://nacos-student
          predicates:
            - Path=/student/**
    nacos:
      discovery:
        server-addr: localhost:8848